---
name: Run Performance Tests

on: [push]

jobs:
  runscript:
    runs-on: ubuntu-latest

    steps:
      - name: GetCode
        uses: actions/checkout@v3

      - name: SetupPython
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Performance Tests
        run: |
          python performance/get_gridded_data/time_1pt_1py.py
