---
name: Run Performance Tests

on:
  workflow_dispatch:
    inputs:
      cache:
        description: "Cache of GPFS"
        required: false
        default: "cold"
      wy:
        description: "Water year of data used for test"
        required: false
        default: "1997"

jobs:
  runscript:
    runs-on: ubuntu-latest

    steps:
      - name: GetCode
        uses: actions/checkout@v3

      - name: SetupPython
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install hf_hydrodata
          python -m pip install pytest

      - name: Run Performance Tests
        run: |
          pytest performance/test_1pt_1wy.py --cache=cold

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: log-artifacts
          path: performance/artifacts/