---
name: Run Performance Tests

on:
  workflow_dispatch:
  schedule:
    # Run at 4am on Mon, Wed Sat
    # Jenkins job runs 5am those days to download results from GitHub Actions
    - cron: '0 4 * * 1'
    - cron: '0 4 * * 3'
    - cron: '0 4 * * 6'

jobs:
  runscript:
    runs-on: ubuntu-latest

    steps:
      - name: GetCode
        uses: actions/checkout@v3

      - name: SetupPython
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install hf_hydrodata
          python -m pip install subsettools
          python -m pip install pytest

      - name: Run Performance Tests
        env:
          TEST_EMAIL_PRIVATE: ${{ secrets.TEST_EMAIL_PRIVATE}}
          TEST_PIN_PRIVATE: ${{ secrets.TEST_PIN_PRIVATE}}      
          TEST_EMAIL_PUBLIC: ${{ secrets.TEST_EMAIL_PUBLIC}}
          TEST_PIN_PUBLIC: ${{ secrets.TEST_PIN_PUBLIC}}      
        run: |
          pytest -s performance/test_1pt_1wy.py --wy=2002 --cache=cold
          pytest -s performance/test_1pt_1wy.py --wy=2002 --cache=hot
          pytest -s performance/test_full_3d_pfb.py --wy=2003 --wy_month=02 --cache=cold
          pytest -s performance/test_full_3d_pfb.py --wy=2003 --wy_month=02 --cache=hot
          pytest -s performance/test_subset_forcing.py --wy=2007 --cache=cold
          pytest -s performance/test_subset_forcing.py --wy=2007 --cache=hot
          pytest -s performance/test_subset_forcing_2mo.py --wy=2007 --cache=cold
          pytest -s performance/test_subset_forcing_2mo.py --wy=2007 --cache=hot
          pytest -s performance/test_subset_forcing_users.py --wy 2009 --cache=cold --users=3
          pytest -s performance/test_subset_forcing_users.py --wy 2009 --cache=hot --users=3
          pytest -s performance/test_hydrogen_forcing.py --wy 1985 --cache=cold --users=-4
          pytest -s performance/test_hydrogen_forcing.py --wy 1985 --cache=hot --users=-4
          pytest -s performance/test_cw3e_subset.py --wy 2019 --cache=cold
          pytest -s performance/test_cw3e_subset.py --wy 2019 --cache=hot
          pytest -s performance/test_1pt_1h.py --wy=1995 --cache=cold
          pytest -s performance/test_1pt_1h.py --wy=1995 --cache=hot         

          echo "Show ./artifacts/log_artifact.csv file"
          cat ./artifacts/log_artifact.csv

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: log-artifacts
          path: ./artifacts/